// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPhtOC9Z_kR-dc8bKxYDGSaxaTDcCXMc',
    appId: '1:820551511814:web:b666a496e48fd7d31df887',
    messagingSenderId: '820551511814',
    projectId: 'fir-store-6f3b1',
    authDomain: 'fir-store-6f3b1.firebaseapp.com',
    storageBucket: 'fir-store-6f3b1.appspot.com',
    measurementId: 'G-LG267N1M64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHXQpYJvWa_H3ezN7YFr_KdOYS0ORqjI',
    appId: '1:820551511814:android:591d632de7b3b6811df887',
    messagingSenderId: '820551511814',
    projectId: 'fir-store-6f3b1',
    storageBucket: 'fir-store-6f3b1.appspot.com',
  );
}
